// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

function getPrefix(env: string | undefined) {
  const map: Record<string, string> = {
    local: 'LOCAL',
    dev: 'DEV',
    prod: 'PROD',
  };
  return map[(env || 'local').toLowerCase()] || 'LOCAL';
}

function getEnvValue(prefix: string, key: string, fallback?: string) {
  const prefixed = process.env[`${prefix}_${key}`];
  if (prefixed !== undefined) return prefixed;
  if (process.env[key] !== undefined) return process.env[key] as string;
  return fallback;
}

const nodeEnv = (process.env.NODE_ENV || 'local').toLowerCase();
const prefix = getPrefix(nodeEnv);
const databaseUrl = getEnvValue(prefix, 'DATABASE_URL', '');

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: 'tsx prisma/seed.ts',
  },
  datasource: {
    url: databaseUrl,
  },
});
